### ISSUE TITLE
Mime type text/html not supported in extent pdf report

### ISSUE THREAD

**Issue by bothikarsk** [grasshopper7/extentreports-cucumberjson-plugin#22]
Getting warning mime type text/html not supported for scenario.attach(byte [] data, "text/html", "name" ) . Html is not added to step definition in extent pdf report. I am using io.cucumber 6.9.1 version.

**Comment by grasshopper7** [comment]
try using scenario.log().

**Comment by bothikarsk** [comment]
I am expecting it to be added as table. For e.g in cucumber masterthought report html table is added for same step. If possible please check if this can be done in pdf report
![IMG20210921180312](https://user-images.githubusercontent.com/47055500/134171218-62531ef0-8808-46b3-9fd7-eb6030326a5d.jpg)

**Comment by grasshopper7** [comment]
Got it now. Interesting. Will try for new release.

**Comment by bothikarsk** [comment]
Thank you

**Comment by bothikarsk** [comment]
@grasshopper7  Hope all is well with you. Please let me know whenever mime type text/html is supported by pdf report.

Thanks,
Santosh.

**Comment by grasshopper7** [comment]
Have not looked at in great detail, but it seems to be a big task. 
There is a artifact available which does the conversion of html to pdf snippets but the main issue is the space constraint of the PDF page.
Will have a detailed look, by the end of this week. Then will be able to make a decision. Thx.

**Comment by grasshopper7** [comment]
An initial implementation is available in repository (2.9.0). It will only support simple table html, no spans or any other stuff. The html snippet has to begin with "<table". I have to put in checks and add a default text display in case of trouble. 

U can try it by building the code. U will need a 3 jars. Just follow the POM dependencies trail.

Should be available in Maven in a couple of days if all goes well.

**Comment by grasshopper7** [comment]
Version 2.9.0 has been uploaded. Should be replicated to Maven soon.

**Comment by bothikarsk** [comment]
Thank you. I will update to latest version and let you know.

**Comment by bothikarsk** [comment]
Hello,
Thank you for all the effort and time you spent on this thread.

Hope all is well with you. Apologies. I was off the work all these while so could not check and respond.

I have tried with maven version 2.9.1 but still observing same behaviour.(Warning with message mime type text/html not supported).

Would you be able to check and advise ?

Thank you again !.

Thanks,
Santosh.
